version: "3"
services:
  # angular-service:
  #   container_name: angular-cypress
  #   build: .
  #   ports:
  #     - "4200:80"
  # this container will run Cypress test using built-in Electron browser
  # e2e-electron:
  #   image: "cypress-angular"
  #   command: "runnonheaded"
  #   volumes:
  #     - ./cypress/cypress/reports_docker/electron/videos:/cypressdocker/cypress/videos
  #     - ./cypress/cypress/reports_docker/electron:/cypressdocker/cypress/reports
  # #     # - ./cypress:/cypress-docker/cypress

  # this container will run Cypress test using Chrome browser
  e2e-chrome:
    image: "cypress-angular"
    command: "testsmokechrome"
    volumes:
      - ./cypress/cypress/reports_docker/chrome/videos:/cypressdocker/cypress/videos
      - ./cypress/cypress/reports_docker/chrome:/cypressdocker/cypress/reports
      # - ./cypress:/cypress-docker/cypress

  # this container will run Cypress test using Firefox browser
  # note that both Chrome and Firefox browsers were pre-installed in the Docker image
  # e2e-firefox:
  #   image: "cypress-angular"
  #   command: "runonfirefox"
  #   volumes:
  #     - ./cypress/reports_docker/firefox/videos:/cypressdocker/cypress/videos
  #     - ./cypress/reports_docker/firefox:/cypressdocker/cypress/reports
  #     - ./cypress:/cypress-docker/cypress

  # this container will run Cypress test using Chrome browser
  e2e-edge:
    image: "cypress-angular"
    command: "testregedge"
    volumes:
      - ./cypress/cypress/reports_docker/edge/videos:/cypressdocker/cypress/videos
      - ./cypress/cypress/reports_docker/edge:/cypressdocker/cypress/reports
      # - ./cypress:/cypress-docker/cypress

    # if you want to debug FF run, pass DEBUG variable like
    environment:
      - DEBUG=cypress:server:browsers:firefox-util,cypress:server:util:process_profiler
    # volumes:
    #   - ./cypress/videos:/cypressdocker/cypress/videos
    #   - ./cypress/reports:/cypressdocker/cypress/reports